### ISSUE TITLE
Duda sobre el inicio de sesión y registro

### ISSUE THREAD

**Issue by jeandv** [rubenqba/certifications#1]
Mi duda es si tengo que hacer definir otras dos rutas para ir de una página a otra para mostrar la vista y poder iniciar sesión o registrarse, pregunto esto ya que no el enunciado no me piden crear otras rutas, solo he hecho las que me pedían, que son estas nada mas:

La aplicación tendrá como rutas predefinidas las siguientes:

/: es la ruta de acceso a la aplicacion, se deja a consideracion del aspirante su diseño y funcionalidad
/books: es la ruta por defecto (home) en la misma se mostrarán los últimos libros publicados
/books/{book_id}: en esta ruta se mostrará la información específica de un libro por su ID (vista detail)
/users/{user_id}: esta ruta mostrará el perfil de usuario por su ID
/users/{user_id}/cart: esta ruta mostrará el carrito de compras de un usuario por su ID
/checkout/{user_id}: esta ruta contendrá el flujo para realizar el pago de los productos seleccionados por ID de usuario

**Comment by rubenqba** [comment]
Hola @jeandv, puedes crear todas las rutas que creas pertinentes. En la descripción solo se hizo énfasis en las más relevantes, pero puedes crear tantas como necesite tu diseño.
