### ISSUE TITLE
Uso del autenticador Keycloak

### ISSUE THREAD

**Issue by YoussefSabbagh** [rubenqba/certifications#2]
Hola Ruben,

Yo no he trabajado con keycloak, instalé las dependencia (@react-keycloak/web y keycloak-js) al usar el método keycloak.login() me muestra esta pantalla 
![image](https://user-images.githubusercontent.com/68627428/206821192-e95fbf6b-2a22-43e8-9e58-4b1bca2428f0.png) y al tratar de usar el metodo keycloack.register() me indica que no existe 
![image](https://user-images.githubusercontent.com/68627428/206821324-81174114-9cfc-48ba-bffd-1d001162ab98.png)

A mi no me llegaron credenciales para hacer el login, me pudes ayudar con el uso del utenticador.

**Comment by rubenqba** [comment]
Hola Youssef, en ningún lado del ejercicio dice que tienes que usar esa
funcionalidad. Te dice que está desactivada porque precisamente está
deshabilitada. Para autenticarte puedes usar el botón de abajo para
autenticarte usando google.
