### ISSUE TITLE
Keycloack

### ISSUE THREAD

**Issue by DecimoGladiador** [rubenqba/certifications#3]
![Captura de pantalla 2022-12-09 223937](https://user-images.githubusercontent.com/42830552/206829435-62b40183-7def-4dc2-88d2-f93a27dc496b.jpg)

Yo tampoco he trabajado con el keycloack y a lo mejor estoy muy perdido.

**Comment by rubenqba** [comment]
@DecimoGladiador efectivamente ese cliente no tiene autorización para usar ese esquema de autenticación.
