### ISSUE TITLE
Duda de keycloak - Page not found al darle al login

### ISSUE THREAD

**Issue by jeandv** [rubenqba/certifications#4]
Hola Ruben, que tal?

Mi duda es que si estoy haciendo algo mal o es porque hubo un fallo, también puede ser que me falto algo pero no se la verdad que seria.

- Lo que me muestra al darle click a un boton que me lleva al login con: keycloak.login()

![Captura de pantalla (197)](https://user-images.githubusercontent.com/90219458/206894705-dda9f7cc-59cc-48c3-8ebf-5c0fae3cb8cd.png)

- Aquí la verdad no se si me falta algo o me olvide de otra cosa, solo he estado siguiendo documentación y algunos videos por youtube.
![Captura de pantalla (198)](https://user-images.githubusercontent.com/90219458/206894763-8ec6ded6-1fe5-42aa-8052-7b4d69d25fb9.png)

Saludos.

**Comment by rubenqba** [comment]
Hola Jean.

Pues no se que responderte si estás usando una configuración que no es la
que te brindaron en el ejercicio.
