### ISSUE TITLE
Datos de pago

### ISSUE THREAD

**Issue by YoussefSabbagh** [rubenqba/certifications#5]
Hola Rubén,
No me queda claro el tema del pago (la validación del pago debe ser en el servidor) y por ahora solo tenemos la clave pública.
Yo puedo capturar los datos de la tarjeta de crédito y los otros datos (productos, cantidades, precios y correo) hacer la validación de la tarjeta del lado del cliente, pero sin la respuesta del servidor no se si la compra fue o no exitosa.
Mi duda, es si consideramos exitosa la compra cuando los datos de la tarjeta son correctos y utilizamos el id que genera cuando capturamos la tarjeta(cardElement) y pasamos al agradecimiento. Por favor me aclaras este punto.

**Comment by rubenqba** [comment]
Se considera exitoso el pago cuando se realiza el cargo correspondiente. No
solo la validación, como explique antes esas “validaciones” las realiza
Stripe automáticamente, luego valida el CVV y posteriormente intenta hacer
el cargo con el proveedor (Mastercard, visa u otro soportado), si todo es
correcto entonces Stripe da por terminada la transacción y redirecciona al
usuario a una url que le debiste haber dado al inicio o en su defecto a
otra para notificar algún error.

**Comment by Mejia1994** [comment]
Rubén, se debe hacer uso de los "price_id"?

**Comment by rubenqba** [comment]
Hola, no creo que se necesite. El `price_id` se usa cuando tienes
registrado productos específicos en Stripe. Pero puedes crear un cobro sin
necesidad de tener registrado un producto.

Para todos, en esta dirección está toda la información necesaria para
lograr la integración.
https://stripe.com/docs/stripe-js/react

**Comment by YoussefSabbagh** [comment]
> Owner

Hola Ruben,

No veo la forma de confirmar el pago sin el secret key del lado del cliente. He revisado la documentación y para intentar hacer el cargo se necesita el secret key y esto se hace del lado del servidor. En el lado del cliente cuando usas el CardElement el te regresa un objeto  como este {
    "id": "pm_1MEGBl2eZvKYlo2CixiuSJt2",
    "object": "payment_method",
    "billing_details": {
        "address": {
            "city": null,
            "country": null,
            "line1": null,
            "line2": null,
            "postal_code": "45666",
            "state": null
        },
        "email": "re@ho.com",
        "name": "Tarjeta de Rechazo ",
        "phone": "9411234567"
    },
    "card": {
        "brand": "visa",
        "checks": {
            "address_line1_check": null,
            "address_postal_code_check": null,
            "cvc_check": null
        },
        "country": "US",
        "exp_month": 1,
        "exp_year": 2024,
        "funding": "credit",
        "generated_from": null,
        "last4": "9995",
        "networks": {
            "available": [
                "visa"
            ],
            "preferred": null
        },
        "three_d_secure_usage": {
            "supported": true
        },
        "wallet": null
    },
    "created": 1670867597,
    "customer": null,
    "livemode": false,
    "type": "card"
}

ya sea que la tarjeta sea valida o invalida. Por lo que no veo como verificar el pago sin el secret key del lado del cliente

**Comment by Mejia1994** [comment]
Rubén, en ese el link de la documentación hace uso de los `PaymentElement` el cual indica que se requiere de un `clientSecret`; esto se puede ver en la línea 11 de index.js que está de ejemplo.

**Comment by jhonson1996** [comment]
amigo [Mejia1994](https://github.com/Mejia1994) como se cuales son los usuarios para ingresar? o hay que registrarse?

**Comment by Mejia1994** [comment]
**jhonson1996** si te referís a keycloak, con la autentificación de Google sirve

**Comment by jhonson1996** [comment]
[Mejia1994](https://github.com/Mejia1994) muchas gracias brou

**Comment by jhonson1996** [comment]
[Mejia1994](https://github.com/Mejia1994) bro si me pude registrar con google pero no me aparecen datos de usuario

**Comment by YoussefSabbagh** [comment]
> [Mejia1994](https://github.com/Mejia1994) bro si me pude registrar con google pero no me aparecen datos de usuario

en el objeto keycloak.idTokenParsed tienes los datos

**Comment by YoussefSabbagh** [comment]
@rubenqba 

Sigo trancado con el tema de la confirmación del pago, he revisado la documentación y no consigo como confirmar el pago sin tener el secret-key.
Por favor me puedes ayudar con esto.
Tengo el boton de checkout y validado la tarjeta, el cvv con el CardElement, tengo el objeto paymentMethod que me retorna stripe.createPaymentMethod. 
Pero no tengo si la tarjeta paso o no (La confirmacion o rechazo del pago por lo que he revisado en la documentación se hace en el servidor y necesita el sk)

**Comment by rubenqba** [comment]
Ok, no hay problema. Ahorita les agrego el secret key a la liga donde se
encuentran los datos de Stripe.

**Comment by rubenqba** [comment]
Hola @YoussefSabbagh y al resto. Ya en la liga que se les compartió esta actualizado el `secret_key` que necesitaban.
