### ISSUE TITLE
duda en la configuracion keycloak

### ISSUE THREAD

**Issue by jhonson1996** [rubenqba/certifications#6]
![configuracion](https://user-images.githubusercontent.com/50467544/207085844-a6d7c0b4-c907-4c69-8c5a-4e6f8ed5d8cc.jpg)

![configuracion1](https://user-images.githubusercontent.com/50467544/207092590-ed9d9696-fc04-4438-9952-1fd3905eba71.jpg)

estoy usando esta configuración y me aparece este error de cors
![error](https://user-images.githubusercontent.com/50467544/207092897-c3768a5b-3dd8-43ec-aebd-876305578c04.jpg)

**Comment by rubenqba** [comment]
Hola @jhonson1996 

Esa dirección que pusiste en tu configuración (
https://auth.gyfted.io/bookstore-client/keycloak.json) no existe. Ese es el
error principal que te está dando en la consola. Creo que no leiste bien
las instrucciones o mal interpretaste como se realiza la configuración.
Nunca he usado la configuración mediante un JSON porque implicaría dejar un
archivo en el control de versiones con los datos sensibles expuestos, pero
supongo que una vez que pongas la dirección correcta de tu archivo de
configuración debería funcionarte.

Salu2

**Comment by jhonson1996** [comment]
ok gracias ya lo resolví, te estaré pregunto
